curl http://www.boardgamegeek.com/xmlapi/boardgame/83068 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27708 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/68448 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/92539 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/217 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/41636 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/5 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31260 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/73833 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/90419 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/17329 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/67877 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/74 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/41541 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/15987 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31449 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/72991 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/69789 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/39683 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/986 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/163 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27225 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/30933 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/3955 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/9653 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66508 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/42444 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/760 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2425 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37111 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/34219 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/10550 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/55165 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/23890 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2453 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/16395 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/11 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/398 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/6420 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/822 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/89952 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/4390 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2993 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/92332 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/7717 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/89953 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/41010 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/5405 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/50381 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/826 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/19237 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/30324 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/18602 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27364 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/3570 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/478 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/22141 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/36560 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1294 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2719 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/891 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/82610 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/88402 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/95234 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/8924 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40793 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2956 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/39856 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/55660 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/92828 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/36218 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/36218 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/90850 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/104557 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40834 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66690 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/51811 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/9408 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66171 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/43315 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/943 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2346 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/58421 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/100423 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/403 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40393 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/258 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/172 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/65244 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/340 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31481 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2921 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/7472 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/28739 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/23686 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66362 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/12692 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37654 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/18207 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/25621 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/16226 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/39872 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2379 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/116 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31512 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2944 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/34707 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/8203 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/8203 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/220 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2655 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2655 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/70704 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/30323 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/4424 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/71272 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/22348 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2750 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37759 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/9674 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/22484 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/265 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/54043 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/28023 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/12002 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2452 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/8098 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/394 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/11971 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/91034 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/257 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/3699 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/33876 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/70323 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/107529 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/97582 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/29368 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/54735 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/38334 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/6608 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/50 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/42487 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/13642 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/22863 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/8127 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/5135 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/29223 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2392 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/39684 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/25568 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31056 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/590 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1406 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40398 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/24764 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/36345 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/38984 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/38984 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/21763 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/55427 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/72287 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1927 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31920 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/6607 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/65907 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/13308 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/92319 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/3737 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37120 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/30549 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40849 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/69552 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/75358 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37000 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/97803 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/45 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/26235 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/4975 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2281 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/22889 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/140 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/140 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2651 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/555 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/39635 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/90919 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/3076 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/67928 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1419 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/91536 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/106895 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/681 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/91984 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/19370 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/624 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/25669 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/12 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/28143 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66121 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40210 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/3449 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27940 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/24310 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/79073 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/41114 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37198 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66056 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37728 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37380 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1260 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/94362 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/9220 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/91072 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/32341 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66214 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/33604 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/92852 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2381 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/320 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1198 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/13 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2807 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/926 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/4101 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/325 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/4103 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27760 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/34691 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/15062 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/35704 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/73 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/8929 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/92415 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/594 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40692 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/97786 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/81618 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/57072 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/57070 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/71818 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27389 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/55601 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/67185 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2407 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/98242 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/79131 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27833 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/34635 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1917 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31612 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/93260 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/65556 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2653 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/96323 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1111 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/46213 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/25613 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/503 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/53953 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/9209 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/53383 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/24439 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/89848 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/14996 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/21348 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31627 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/42 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/54 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/67180 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/37141 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/36553 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/42215 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/382 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/56835 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2842 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/16267 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/73439 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/58707 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/12333 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/31999 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/16986 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/29073 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/7601 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/41002 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/99120 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/11412 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/33154 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/67178 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/44614 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/9203 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/66588 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/20100 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/1465 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/40990 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/63778 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2243 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/7854 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/528 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/89575 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/29387 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/2471 >> D:\boardgamegeek\inventoryBGG
curl http://www.boardgamegeek.com/xmlapi/boardgame/27588 >> D:\boardgamegeek\inventoryBGG
fart --c-style D:\boardgamegeek\inventoryBGG "</boardgames><boardgames termsofuse=\"http://boardgamegeek.com/xmlapi/termsofuse\">" " "
